/**
 * API FEATURES UTILITY
 * This class provides advanced query capabilities for MongoDB:
 * - Filtering (e.g., price[gte]=500)
 * - Sorting (e.g., sort=price,-ratingsAverage)
 * - Field Limiting (e.g., fields=name,duration)
 * - Pagination (e.g., page=2&limit=10)
 */
class APIFeatures {
  /**
   * @param {Object} query - The Mongoose Query object (e.g., Tour.find()).
   * @param {Object} params - The raw request query parameters (req.query).
   * @param {Object} formattedParams - Query object after operator conversion ($gte, etc.).
   */
  constructor(query, params, formattedParams) {
    this.query = query;
    this.params = params;
    this.formattedParams = formattedParams;
  }

  /**
   * FILTERING
   * Applies MongoDB filtering based on the formatted parameters.
   * @returns {APIFeatures} - Returns this instance for method chaining.
   */
  filter() {
    // formattedParams already contains MongoDB operators ($gte, $lt, etc.) 
    // generated by formatQuery middleware.
    const queryObj = { ...this.formattedParams };
    this.query = this.query.find(queryObj);

    return this;
  }

  /**
   * SORTING
   * Sorts the results based on the 'sort' query parameter.
   * Format: ?sort=price,-ratingsAverage
   * @returns {APIFeatures}
   */
  sort() {
    if (this.params.sort) {
      // Convert 'price,-ratingsAverage' to 'price -ratingsAverage'
      const sortBy = this.params.sort.split(",").join(" ");
      this.query = this.query.sort(sortBy);
    } else {
      // Default sorting: Newest first
      this.query = this.query.sort("-createdAt");
    }

    return this;
  }

  /**
   * FIELD LIMITING (PROJECTION)
   * Limits the fields returned for each document to optimize bandwidth.
   * Format: ?fields=name,duration,price
   * @returns {APIFeatures}
   */
  limit() {
    if (this.params.fields) {
      // Convert 'name,duration' to 'name duration'
      const fields = this.params.fields.split(",").join(" ");
      this.query = this.query.select(fields);
    } else {
      // Default: Exclude the __v field which Mongoose uses for versioning
      this.query = this.query.select("-__v");
    }

    return this;
  }

  /**
   * PAGINATION
   * Implements pagination using skip() and limit().
   * Format: ?page=2&limit=10
   * @returns {APIFeatures}
   */
  pagination() {
    // Convert strings to numbers and set defaults
    const page = Number(this.params.page) || 1;
    const limitVal = Number(this.params.limit) || 10;
    
    // Calculate skip value (e.g., Page 2 with limit 10 skips first 10 docs)
    const skip = (page - 1) * limitVal;

    this.query = this.query.skip(skip).limit(limitVal);

    return this;
  }
}

module.exports = APIFeatures;

